version: 2.1

orbs:
  telemetry:
    orbs:
      rebar3: tsloughter/rebar3@0.5.5
      codecov: codecov/codecov@1.0.2

    jobs:
      build_and_test:
        parameters:
          version:
            description: The Erlang/OTP docker image tag to use.
            type: string
          pkg_install_cmd:
            type: string
            default: apk add --no-cache
          coverage:
            type: string
            default: \"\"
        executor:
          name: rebar3/erlang
          version: <<parameters.version>>
        steps:
          - rebar3/install_ca_certs:
              pkg_install_cmd: <<parameters.pkg_install_cmd>>
          - checkout
          - rebar3/with_deps_cache:
              cache_key_postfix: -<<parameters.version>>
              steps:
                - rebar3/compile
                - rebar3/dialyzer
                - rebar3/xref
                - rebar3/ct

                - store_test_results:
                    path: ~/project/_build/test/logs/
                - store_artifacts:
                    path: ~/project/_build/test/logs
                    destination: common_test

                - rebar3/cover
                - run: rebar3 as test covertool generate
                - run:
                    name: Install curl
                    command: <<parameters.pkg_install_cmd>> curl
                - codecov/upload:
                    file: _build/test/covertool/telemetry.covertool.xml
                    flags: '${CIRCLE_JOB},'

workflows:
  build_and_test:
    jobs:
      - telemetry/build_and_test:
          name: "otp-21"
          version: "21-alpine"
      - telemetry/build_and_test:
          name: "otp-20"
          version: "20-alpine"
      - telemetry/build_and_test:
          name: "otp-19"
          version: "19"
          pkg_install_cmd: "apt-get update && apt-get install"
      - telemetry/build_and_test:
          name: "otp-18"
          version: "18"
          pkg_install_cmd: "apt-get update && apt-get install"
